version: '3.7'

networks:
  laravel:

  services:
    nginx:
      image: nginx:stable-alpine
      container_name: laravel_nginx
      ports:
        - "82:80"
      volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      network:
        - laravel

    mysql:
      images: mysql:5.7.22
      container_name: laravel_mysql
      restart: unless-stopped
      tty: true
      ports: 
        - "3306:3306"
      volumes: 
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      network:
        - laravel

    php:
      build:
        context: .
        dockerfile: Dockerfile
        container_name: laravel_php
        volumes:
          - ./src:/var/www/html
        ports:
          - "9000:9000"
      network:
        - laravel